# Generated by Django 4.2.13 on 2024-06-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('categoria', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
                ('consola', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
