# Generated by Django 4.2.13 on 2024-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_accesorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
