# Generated by Django 4.2.13 on 2024-06-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_categoria_alter_carro_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='stock',
        ),
    ]
