# Generated by Django 4.2.13 on 2024-06-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_remove_carro_categoria_remove_carro_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
