# Generated by Django 5.0.1 on 2024-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_alter_carro_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagen',
            field=models.FileField(default='Images/juego6.jpg', upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.FileField(default='Images/juego6.jpg', upload_to='imagenes/'),
        ),
    ]
