# Generated by Django 4.2.13 on 2024-06-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_usuario_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.FileField(default='Images/juego6.jpg', upload_to='imagenes/'),
        ),
    ]
