# Generated by Django 4.2.13 on 2024-06-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_rename_id_carro_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='id',
            field=models.BigAutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='id2',
            field=models.CharField(max_length=100),
        ),
    ]
