# Generated by Django 4.2.13 on 2024-06-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0013_carro_id_alter_carro_id2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
