# Generated by Django 4.2.13 on 2024-06-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0014_alter_carro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
