# Generated by Django 4.2.13 on 2024-06-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0016_consola_formapago_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.IntegerField(default=1),
        ),
    ]
