# Generated by Django 4.2.13 on 2024-06-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0017_categoria_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='consola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.consola'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='consola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.consola'),
        ),
    ]
