# Generated by Django 4.2.13 on 2024-06-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0018_alter_accesorios_consola_alter_producto_consola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='consola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.consola'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='consola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.consola'),
        ),
    ]
