# Generated by Django 4.2.13 on 2024-06-25 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0021_usuarioactual'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFalso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('rut', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=50)),
                ('nacimiento', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=300)),
                ('contraseña', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('imagen', models.FileField(default='Images/juego6.jpg', upload_to='imagenes/')),
                ('tipoUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.tipousuario')),
            ],
        ),
    ]
