# Generated by Django 4.2.13 on 2024-06-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0022_usuariofalso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofalso',
            name='tipoUsuario',
        ),
        migrations.DeleteModel(
            name='UsuarioActual',
        ),
        migrations.DeleteModel(
            name='UsuarioFalso',
        ),
    ]
